/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPropostasIndexRouteImport } from './routes/_authenticated/propostas.index'
import { Route as AuthenticatedPropostasNovaRouteImport } from './routes/_authenticated/propostas.nova'
import { Route as AuthenticatedPropostasIdRouteImport } from './routes/_authenticated/propostas.$id'
import { Route as AuthenticatedPropostasIdEditarRouteImport } from './routes/_authenticated/propostas.$id.editar'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPropostasIndexRoute =
  AuthenticatedPropostasIndexRouteImport.update({
    id: '/propostas/',
    path: '/propostas/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPropostasNovaRoute =
  AuthenticatedPropostasNovaRouteImport.update({
    id: '/propostas/nova',
    path: '/propostas/nova',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPropostasIdRoute =
  AuthenticatedPropostasIdRouteImport.update({
    id: '/propostas/$id',
    path: '/propostas/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPropostasIdEditarRoute =
  AuthenticatedPropostasIdEditarRouteImport.update({
    id: '/editar',
    path: '/editar',
    getParentRoute: () => AuthenticatedPropostasIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/propostas/$id': typeof AuthenticatedPropostasIdRouteWithChildren
  '/propostas/nova': typeof AuthenticatedPropostasNovaRoute
  '/propostas/': typeof AuthenticatedPropostasIndexRoute
  '/propostas/$id/editar': typeof AuthenticatedPropostasIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/propostas/$id': typeof AuthenticatedPropostasIdRouteWithChildren
  '/propostas/nova': typeof AuthenticatedPropostasNovaRoute
  '/propostas': typeof AuthenticatedPropostasIndexRoute
  '/propostas/$id/editar': typeof AuthenticatedPropostasIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/propostas/$id': typeof AuthenticatedPropostasIdRouteWithChildren
  '/_authenticated/propostas/nova': typeof AuthenticatedPropostasNovaRoute
  '/_authenticated/propostas/': typeof AuthenticatedPropostasIndexRoute
  '/_authenticated/propostas/$id/editar': typeof AuthenticatedPropostasIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/login'
    | '/dashboard'
    | '/onboarding'
    | '/propostas/$id'
    | '/propostas/nova'
    | '/propostas/'
    | '/propostas/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/dashboard'
    | '/onboarding'
    | '/propostas/$id'
    | '/propostas/nova'
    | '/propostas'
    | '/propostas/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cadastro'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/_authenticated/propostas/$id'
    | '/_authenticated/propostas/nova'
    | '/_authenticated/propostas/'
    | '/_authenticated/propostas/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/propostas/': {
      id: '/_authenticated/propostas/'
      path: '/propostas'
      fullPath: '/propostas/'
      preLoaderRoute: typeof AuthenticatedPropostasIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/propostas/nova': {
      id: '/_authenticated/propostas/nova'
      path: '/propostas/nova'
      fullPath: '/propostas/nova'
      preLoaderRoute: typeof AuthenticatedPropostasNovaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/propostas/$id': {
      id: '/_authenticated/propostas/$id'
      path: '/propostas/$id'
      fullPath: '/propostas/$id'
      preLoaderRoute: typeof AuthenticatedPropostasIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/propostas/$id/editar': {
      id: '/_authenticated/propostas/$id/editar'
      path: '/editar'
      fullPath: '/propostas/$id/editar'
      preLoaderRoute: typeof AuthenticatedPropostasIdEditarRouteImport
      parentRoute: typeof AuthenticatedPropostasIdRoute
    }
  }
}

interface AuthenticatedPropostasIdRouteChildren {
  AuthenticatedPropostasIdEditarRoute: typeof AuthenticatedPropostasIdEditarRoute
}

const AuthenticatedPropostasIdRouteChildren: AuthenticatedPropostasIdRouteChildren =
  {
    AuthenticatedPropostasIdEditarRoute: AuthenticatedPropostasIdEditarRoute,
  }

const AuthenticatedPropostasIdRouteWithChildren =
  AuthenticatedPropostasIdRoute._addFileChildren(
    AuthenticatedPropostasIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPropostasIdRoute: typeof AuthenticatedPropostasIdRouteWithChildren
  AuthenticatedPropostasNovaRoute: typeof AuthenticatedPropostasNovaRoute
  AuthenticatedPropostasIndexRoute: typeof AuthenticatedPropostasIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPropostasIdRoute: AuthenticatedPropostasIdRouteWithChildren,
  AuthenticatedPropostasNovaRoute: AuthenticatedPropostasNovaRoute,
  AuthenticatedPropostasIndexRoute: AuthenticatedPropostasIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
